### ISSUE TITLE
Hi, not found url on custom admin url

### ISSUE THREAD

**Issue by hgati** [magento-hackathon/Sandfox_GeoIP#13]
I'm using my own custom admin url.
```xml
<!-- app/etc/local.xml -->
<config>
    <admin>
        <routers>
            <adminhtml>
                <args>
                    <frontName><![CDATA[backend]]></frontName>
                </args>
            </adminhtml>
        </routers>
    </admin>
</config>
```
It doesn't work a synchronize button on system/general/general/country options.
(not found router)

I've commented on your source code.
https://github.com/tim-bezhashvyly/geoip/commit/513bb0fe4480556f1916862e1c610b37e69adcd0

then works.

**Comment by sprankhub** [comment]
This has been fixed with https://github.com/magento-hackathon/Sandfox_GeoIP/commit/05adda7ce9a55234c56e7b29c2b79e8cdc258e70.
