### ISSUE TITLE
Quick question to add a block on front page

### ISSUE THREAD

**Issue by seansan** [magento-hackathon/Sandfox_GeoIP#19]
Hi, there - this looks quite good. THanks!

Support I want to add a block to my front page that states something like

_Welcome to this store. We also deliver to {{COUNTRY NAME}}_
or 
_Welcome to this store. We also deliver to {{CITY NAME}} in {{COUNTRY NAME}}_

Can this be done easily? 
- is there an easy way to add the block? or can we create a block manually?
- would it be an idea to add such a block or variable via the extension? (so we _only need_ to add an XML update to show the code somewhere)
- and where the city name and country name is the complete name that the customer recognizes (not DE or GB)

Hope you can help

Thanks, Sean

**Comment by L9Nick** [comment]
You're a badass, thanks so much!
