### ISSUE TITLE
Need to display content, or hide content based on country, not using config settings. 

### ISSUE THREAD

**Issue by L9Nick** [magento-hackathon/Sandfox_GeoIP#21]
First, thanks so much I think your module it seems like a perfect fit for our need. We sell winter ski gear to CA/AU/NZ. Some of our vendors have restrictions on what we can and can not sell, but other items we sell down under have no restrictions. So I cannot use the built in Magento feature to disable the country. I just need a simple way to show and hide content, cart buttons etc based on their country. 

Is there anyway to just display something based on their ISO country code using your module? Any code example would be greatly appreciated. Thanks again for this FREE awesome mod.

**Comment by tim-bezhashvyly** [comment]
```php
$geoIP = Mage::getSingleton('geoip/country');

if (in_array($geoIP->getCountry(), ['CA', 'AU', 'NZ']) {
    // do something
}
```

**Comment by L9Nick** [comment]
Thanks again for the help, posted the last one in the wrong place. Cheers.
