### ISSUE TITLE
Getting State/City

### ISSUE THREAD

**Issue by gety9** [magento-hackathon/Sandfox_GeoIP#32]
Guys, can i use this extension to work with GeoLite City?

I need to get state value.

On GeoIP2-php page they provided the following example

```
$record = $reader->city('128.101.101.101');

print($record->mostSpecificSubdivision->name . "\n"); // 'Minnesota'
print($record->mostSpecificSubdivision->isoCode . "\n"); // 'MN'

print($record->city->name . "\n"); // 'Minneapolis'

print($record->postal->code . "\n"); // '55455'
```
Can i make it work with this extension?

**Comment by sprankhub** [comment]
You can of course "make it work" somehow, but it does not work out of the box. This extension is meant to be used with the country database.
