### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by scottcdi** [magento-hackathon/Sandfox_GeoIP#33]
Magento just recently announced that they will be openly supporting PHP 7.2 for the magento 1 instance and have also recently just released a patch.

Does anyone know if this plugin will be compatible with PHP 7.2 or if a patch is planning on being developed here as well?

**Comment by sprankhub** [comment]
I cannot tell for sure, but there are only rare cases, where PHP 7.2 really leads to issues. I am pretty much sure that this extension will work flawlessly with PHP 7.2. If you encounter any issues, feel free to reopen.
